[package]
name = "servo-integration"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "servo-integration"
path = "src/main.rs"

[dependencies]
url = "2.5.2"
smol = "2.0.2"
winit = "0.30"
rustls = "0.23"
euclid = "0.22.11"

slint = { git = "https://github.com/slint-ui/slint", features = [
    "unstable-winit-030",
] }

webrender_api = { git = "https://github.com/servo/webrender", branch = "0.67" }

libservo = { git = "https://github.com/servo/servo", rev = "b73c81630ab1d1e1a931dca84d70f997c12c286b" }
embedder_traits = { git = "https://github.com/servo/servo", rev = "b73c81630ab1d1e1a931dca84d70f997c12c286b", features = [
    "baked-default-resources",
] }
