import {VerticalBox, Button, HorizontalBox} from "std-widgets.slint";

export component MyApp inherits Window {
    width: 1224px;
    height: 768px;

    in property <image> web_content <=> image.source;

    out property <length> mouse_x <=> touch_area.mouse-x;
    out property <length> mouse_y <=> touch_area.mouse-y;

    callback scroll_event(length, length);
    callback pointer_event(PointerEvent);

    VerticalBox {
        padding: 0px;
        spacing: 0px;

        HorizontalBox {
            height: 50px;
            padding: 8px;
            spacing: 8px;

            Button {
                horizontal-stretch: 0;
                text: "Back";
            }

            Button {
                text: "Forward";
            }

            Button {
                text: "Reload";
            }

            Rectangle {
                background: #636366;
                border-radius: 4px;
                TextInput {
                    text: "Url Bar";
                    horizontal-stretch: 1;
                    vertical-alignment: TextVerticalAlignment.center;
                }
            }

            Button {
                text: "Go";
            }
        }

        touch_area := TouchArea {
            image := Image {
                width: 100%;
                height: 100%;
            }

            pointer-event(event) => {
                pointer_event(event);
            }
            scroll-event(event) => {
                scroll_event(event.delta-x, event.delta-y);
                return accept;
            }
        }
    }
}
