import {VerticalBox, HorizontalBox, Button, LineEdit} from "std-widgets.slint";

export component MyApp inherits Window {
    preferred-width: 1224px;
    preferred-height: 768px;

    in property <image> web_content <=> image.source;

    out property <length> viewport_width <=> touch_area.width;
    out property <length> viewport_height <=> touch_area.height;

    out property <length> mouse_x <=> touch_area.mouse-x;
    out property <length> mouse_y <=> touch_area.mouse-y;

    callback scroll_event(x: length, y: length);
    callback pointer_event(event: PointerEvent);
    callback resize(width: length, height: length);

    callback back();
    callback forward();
    callback reload();
    callback go();

    VerticalBox {
        padding: 0px;
        spacing: 0px;

        HorizontalBox {
            height: 50px;
            padding: 8px;
            spacing: 8px;

            Button {
                text: "Back";
                clicked => {
                    back();
                }
            }

            Button {
                text: "Forward";
                clicked => {
                    forward();
                }
            }

            Button {
                text: "Reload";
                clicked => {
                    reload();
                }
            }

            LineEdit {
                text: "Urlbar";
                horizontal-stretch: 1;
            }

            Button {
                text: "Go";
                clicked => {
                    go();
                }
            }
        }

        touch_area := TouchArea {

            image := Image {
                width: 100%;
                height: 100%;
            }

            changed width => {
                resize(self.width, self.height);
            }
            changed height => {
                resize(self.width, self.height);
            }

            pointer-event(event) => {
                pointer_event(event);
            }
            scroll-event(event) => {
                scroll_event(event.delta-x, event.delta-y);
                return accept;
            }
        }
    }
}
