import {VerticalBox, HorizontalBox, Button, LineEdit} from "std-widgets.slint";

export global WebviewLogic {

    callback scroll_event(x: length, y: length, mouse_x: length, mouse_y: length);
    callback pointer_event(event: PointerEvent, mouse_x: length, mouse_y: length);
    callback resize(width: length, height: length);

    in property <image> web_content;

    out property <length> viewport_width: 800px;
    out property <length> viewport_height: 400px;

    out property <length> mouse_x;
    out property <length> mouse_y;
}

component Webview {

    touch_area := TouchArea {

        image := Image {
            source: WebviewLogic.web_content;
            width: 100%;
            height: 100%;
        }

        changed width => {
            WebviewLogic.resize(self.width, self.height);
        }
        changed height => {
            WebviewLogic.resize(self.width, self.height);
        }

        pointer-event(event) => {
            WebviewLogic.pointer_event(event, self.mouse-x, self.mouse-y);
        }
        scroll-event(event) => {
            WebviewLogic.scroll_event(event.delta-x, event.delta-y, self.mouse-x, self.mouse-y);
            return accept;
        }
    }
}

export component MyApp inherits Window {
    preferred-width: 1224px;
    preferred-height: 768px;

    callback back();
    callback forward();
    callback reload();
    callback go();

    VerticalBox {
        padding: 0px;
        spacing: 0px;

        HorizontalBox {
            height: 50px;
            padding: 8px;
            spacing: 8px;

            Button {
                text: "Back";
                clicked => {
                    back();
                }
            }

            Button {
                text: "Forward";
                clicked => {
                    forward();
                }
            }

            Button {
                text: "Reload";
                clicked => {
                    reload();
                }
            }

            LineEdit {
                text: "Urlbar";
                horizontal-stretch: 1;
            }

            Button {
                text: "Go";
                clicked => {
                    go();
                }
            }
        }

        Rectangle {
            Webview {
                width: 100%;
                height: 100%;
            }
        }
    }
}
